# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31e1179b14136570408c6d023e46d37563bbedf729e78a574b349b0ca41cee1dbe40819ad3275bc3bac90c8ccfc5854c96b5a35a6b6164621d8e41a087c91327

test:
  secret_key_base: d8063d8fb70041561d28f737fd467b58c839841a7077b7d76fac05c89202db4863c4ba48f80fab9df5908e26e21758302d9a9122f60fe5b8b764989c9d5ccf34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
